#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

site_url = 'http://adietados365dias.blogs.sapo.pt/tag/vegetariano'
rss_file = ENV['HOME'] + '/public_html/vitorgalvao/feeds/adietados365dias.rss'

# parse post
page = Nokogiri::HTML(URI.parse(site_url).open)
recepy = page.at('article')
title = recepy.at('h2').text
link = recepy.at('h2').at('a').attr('href')
recepy.search('div, nav, p.metadata').remove

# fix image src
img = recepy.at('img')
img_data_src = img.attr('data-src')
img.attributes['src'].value = img_data_src

# create new feed (if it doesn't exist)
# or prepare existing one (checking if retried item is new)
if !File.file?(rss_file)
  tmp_feed = Nokogiri::XML::Builder.new do |xml|
    xml.rss('version' => '2.0') {
      xml.channel {
        xml.title 'A dieta dos 365 dias'
        xml.link site_url
        xml.description 'RSS feed of the Vegan tagged posts from “A dieta dos 365 dias”'
      }
    }
  end
  rss_feed = Nokogiri::XML(tmp_feed.to_xml)
else
  rss_feed = Nokogiri::XML(File.open(rss_file))

  # abort if most recent item title is the same as the newly retrieved one
  # else save the most recent for later, and continue
  most_recent_title_description = rss_feed.at('item').at('title').content
  if (most_recent_title_description == title)
    puts 'There are no new items to add'
    exit 0
  else
    recent_items = rss_feed.css('item')[0..9] # save recent items
    rss_feed.css('item').remove # removes all items
  end
end

# add new item to feed
Nokogiri::XML::Builder.with(rss_feed.at('channel')) do |xml|
  xml.item {
    xml.title title
    xml.link link
    xml.description recepy.inner_html
  }
end

# add previously grabbed items (if any) and save
rss_feed.at('channel').add_child(recent_items) unless recent_items.nil?

File.open(rss_file, 'w') do |f|
  f.puts rss_feed.to_xml
end
