#!/usr/bin/env ruby

require 'nokogiri'
require 'open-uri'

site_url = 'https://forum.affinity.serif.com/index.php?/topic/10075-affinity-photo-feature-roadmap/'
rss_file = ENV['HOME'] + '/public_html/vitorgalvao/feeds/affinityphotoroadmap.rss'

# parse post
page = Nokogiri::HTML(URI.parse(site_url).open)
post_text = page.at('article').at('div[data-role="commentContent"]').inner_html.strip

# create new feed (if it doesn't exist)
# or prepare existing one (checking if retried item is new)
if !File.file?(rss_file)
  tmp_feed = Nokogiri::XML::Builder.new do |xml|
    xml.rss('version' => '2.0') {
      xml.channel {
        xml.title 'Affinity Photo Roadmap'
        xml.link site_url
        xml.description 'RSS feed of the first forum post of Affinity Photo’s feature roadmap'
      }
    }
  end
  rss_feed = Nokogiri::XML(tmp_feed.to_xml)
else
  rss_feed = Nokogiri::XML(File.open(rss_file))

  # abort if most recent item description is the same as the newly retrieved one
  # else save the most recent for later, and continue
  most_recent_item_description = rss_feed.at('item').at('description').content
  if (most_recent_item_description == post_text)
    puts 'There are no new items to add'
    exit 0
  else
    recent_items = rss_feed.css('item')[0..9] # save recent items
    rss_feed.css('item').remove # removes all items
  end
end

# add new item to feed
Nokogiri::XML::Builder.with(rss_feed.at('channel')) do |xml|
  xml.item {
    xml.title 'Updated feature roadmap'
    xml.link site_url
    xml.description post_text
  }
end

# add previously grabbed items (if any) and save
rss_feed.at('channel').add_child(recent_items) unless recent_items.nil?

File.open(rss_file, 'w') do |f|
  f.puts rss_feed.to_xml
end
