#!/usr/bin/env ruby

require 'open-uri'
require 'nokogiri'

site_url = 'https://forum.affinity.serif.com/index.php?/topic/51629-affinity-designer-customer-beta'
rss_file = ENV['HOME'] + '/public_html/vitorgalvao/rss/affinitydesignerbetafeatures.rss'

# parse post
page = Nokogiri::HTML(open(site_url))
post_title = page.at('h1.ipsType_pageTitle').text.strip
post_text = page.at('article').at('div[data-role="commentContent"]').inner_html.strip

# create new feed (if it doesn't exist)
# or prepare existing one (checking if retried item is new)
if !File.file?(rss_file)
  tmp_feed = Nokogiri::XML::Builder.new do |xml|
    xml.rss('version' => '2.0') {
      xml.channel {
        xml.title 'Affinity Designer Beta Features'
        xml.link site_url
        xml.description 'RSS feed of the first forum post of Affinity Designer’s beta features'
      }
    }
  end
  rss_feed = Nokogiri::XML(tmp_feed.to_xml)
else
  rss_feed = Nokogiri::XML(File.open(rss_file))

  # abort if most recent item title is the same as the newly retrieved one
  # else save the most recent for later, and continue
  most_recent_item_title = rss_feed.at('item').at('title').content
  if (most_recent_item_title == post_title)
    puts 'There are no new items to add'
    exit 0
  else
    recent_items = rss_feed.css('item')[0..9] # save recent items
    rss_feed.css('item').remove # removes all items
  end
end

# add new item to feed
Nokogiri::XML::Builder.with(rss_feed.at('channel')) do |xml|
  xml.item {
    xml.title post_title
    xml.link site_url
    xml.description post_text
  }
end

# add previously grabbed items (if any) and save
rss_feed.at('channel').add_child(recent_items) unless recent_items.nil?

File.open(rss_file, 'w') do |f|
  f.puts rss_feed.to_xml
end
