#!/usr/bin/env ruby

require 'open-uri'
require 'nokogiri'

site_page = 'http://www.penny-arcade.com/comic'
rss_file = ENV['HOME'] + '/public_html/vitorgalvao/rss/pennyarcade.rss'

# get new comic
page = Nokogiri::HTML(open(site_page))
description_page_url = page.at('.comicTag a').attr('href')
description_page = Nokogiri::HTML(open(description_page_url))

comic_title = page.at('.comicTag h2').text
comic_link = description_page_url.sub('/news/post/', '/comic/')
comic_image = page.at('#comicFrame img').attr('src')
comic_description = description_page.at('.copy').inner_html

# create new feed (if it doesn't exist)
# or prepare existing one (checking if retried item is new)
if !File.file?(rss_file)
  tmp_feed = Nokogiri::XML::Builder.new do |xml|
    xml.rss('version' => '2.0') {
      xml.channel {
        xml.title 'Penny Arcade'
        xml.link site_page
        xml.description 'Penny Arcade comic'
      }
    }
  end
  rss_feed = Nokogiri::XML(tmp_feed.to_xml)
else
  rss_feed = Nokogiri::XML(File.open(rss_file))

  # abort if most recent item link is the same as the newly retrieved one
  # else save the most recent for later, and continue
  most_recent_item_link = rss_feed.at('item').at('link').content
  if (most_recent_item_link == comic_link)
    abort 'There are no new items to add'
  else
    recent_items = rss_feed.css('item')[0..9] # save recent items
    rss_feed.css('item').remove # removes all items
  end
end

# add new item to feed
Nokogiri::XML::Builder.with(rss_feed.at('channel')) do |xml|
  xml.item {
    xml.title comic_title
    xml.link comic_link
    xml.description "<img src='#{comic_image}'>#{comic_description}"
  }
end

# add previously grabbed items (if any) and save
rss_feed.at('channel').add_child(recent_items) unless recent_items.nil?

File.open(rss_file, 'w') do |f|
  f.puts rss_feed.to_xml
end
