#!/usr/bin/env ruby

require 'json'
require 'nokogiri'
require 'open-uri'
require 'pathname'
require 'rss'

# Required environment variables
begin
  Feed_local_dir = Pathname(ENV['FEED_LOCAL_DIR'])
  Feed_web_dir = Pathname(ENV['FEED_WEB_DIR'])

  unless Feed_local_dir.directory? &&
         Feed_web_dir
    raise Errno::ENOENT
  end
rescue TypeError, Errno::ENOENT
  abort <<~ERROR
    Some required environment variables are not set correctly.
    Full list to verify:

    FEED_LOCAL_DIR: path to directory to read and write feed
    FEED_WEB_DIR: url to web directory hosting the feed
  ERROR
end

# Configure feed info
site_url = 'https://www.theguardian.com/lifeandstyle/series/thiscolumnwillchangeyourlife/rss'
feed_title = 'This Column Will Change Your Life'
feed_name = 'thiscolumnwillchangeyourlife'

feed_file = Feed_local_dir.join("#{feed_name}.json")
feed_location = Feed_web_dir.join("#{feed_name}.json")

feed = {
  version: 'https://jsonfeed.org/version/1',
  title: feed_title,
  home_page_url: site_url,
  feed_url: feed_location
}

# Leave as is. Preparing the feed.
feed_new = {}
feed_new['items'] = []
feed_old = JSON.parse(feed_file.read) rescue { 'items' => [] }
feed_old_first_url = feed_old['items'][0]['url'] rescue ''

# Strategy for getting new items
latest_issues = RSS::Parser.parse(URI.parse(site_url).open).items

latest_issues.each do |issue|
  issue_url = issue.link

  # Stop adding once we reach the latest already present
  break if issue_url == feed_old_first_url

  issue_title = issue.title
  issue_page = Nokogiri::HTML(URI.parse(issue_url).open)
  issue_full = issue_page.at('.content__main-column--article')
  issue_tagline = issue_full.at('p').text
  issue_image = issue_full.at('picture').at('source').attr('srcset').sub(/ \d+w$/, '')

  # Remove extraneous nodes
  issue_full.search('aside').remove
  issue_full.search('header').remove
  issue_full.search('.submeta').remove

  item_content = "<p><i>#{issue_tagline}</i></p><img src='#{issue_image}'>" + issue_full.inner_html

  feed_new['items'].push(title: issue_title, id: issue_url, url: issue_url, content_html: item_content)
end

# If there are no new items, inform and exit
if feed_new['items'].empty?
  puts 'There are no new items to add'
  exit 0
end

# Prepend new items to the old and limit the amount of items
feed['items'] = (feed_new['items'] + feed_old['items']).first(20)

feed_file.write(JSON.pretty_generate(feed))
