#!/usr/bin/env ruby

require 'json'
require 'nokogiri'
require 'pathname'
require 'rss'

# Require environment variables
abort 'You need to set a "FEED_EXPORT_LOCATION" environment variable pointing to a writable directory' unless ENV['FEED_EXPORT_LOCATION'] && Dir.exist?(ENV['FEED_EXPORT_LOCATION']) && File.writable?(ENV['FEED_EXPORT_LOCATION'])

abort 'You need to set a "FEED_ONLINE_LOCATION" environment variable pointing to the web directory path where the feed will be accessible from' unless ENV['FEED_ONLINE_LOCATION']

# Configure feed info
site_url = 'https://www.theguardian.com/lifeandstyle/series/thiscolumnwillchangeyourlife/rss'
feed_title = 'This Column Will Change Your Life'
feed_name = 'thiscolumnwillchangeyourlife'

feed_file = Pathname(ENV['FEED_EXPORT_LOCATION']).join("#{feed_name}.json")
feed_location = URI.join(ENV['FEED_ONLINE_LOCATION'], "#{feed_name}.json")

feed = {
  version: 'https://jsonfeed.org/version/1',
  title: feed_title,
  home_page_url: site_url,
  feed_url: feed_location.to_s
}

# Leave as is. Preparing the feed.
feed_new = {}
feed_new['items'] = []
feed_old = JSON.parse(feed_file.read) rescue { 'items' => [] }
feed_old_first_url = feed_old['items'][0]['url'] rescue ''

# Strategy for getting new items
latest_issues = RSS::Parser.parse(URI.parse(site_url).open).items

latest_issues.each do |issue|
  issue_url = issue.link

  # Stop adding once we reach the latest already present
  break if issue_url == feed_old_first_url

  issue_title = issue.title
  issue_page = Nokogiri::HTML(URI.parse(issue_url).open)
  issue_full = issue_page.at('.content__main-column--article')
  issue_tagline = issue_full.at('p').text
  issue_image = issue_full.at('picture').at('source').attr('srcset').sub(/ \d+w$/, '')

  # Remove extraneous nodes
  issue_full.search('aside').remove
  issue_full.search('header').remove
  issue_full.search('.submeta').remove

  item_content = "<p><i>#{issue_tagline}</i></p><img src='#{issue_image}'>" + issue_full.inner_html

  feed_new['items'].push(title: issue_title, id: issue_url, url: issue_url, content_html: item_content)
end

# If there are no new items, inform and exit
if feed_new['items'].empty?
  puts 'There are no new items to add'
  exit 0
end

# Prepend new items to the old and limit the amount of items
feed['items'] = (feed_new['items'] + feed_old['items']).first(20)

feed_file.write(JSON.pretty_generate(feed))
